server:
  port: 8080
spring:
  application:
    name: springboot3-demo
  data:
    redis:
      host: 192.168.101.209
      port: 6379
      database: 0
      password: r@In4ugust
    mongodb:
      database: springboot3_test
      host: 192.168.101.209
      port: 27017
  elasticsearch:
    uris: 192.168.101.209:9200
  kafka:
    bootstrap-servers: 192.168.101.209:9092
    consumer:
      group-id: test-consumer-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 10
      auto-offset-reset: earliest
      auto-commit-interval: 1000
    producer:
      acks: 1
      batch-size: 4096
      buffer-memory: 40960000
      client-id: test-producer-1
      compression-type: zstd
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        spring.json.add.type.headers: false
        max.request.size: 126951500
    listener:
      missing-topics-fatal: false
      ack-mode: manual_immediate
      concurrency: 1
      type: batch



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.209:3306/springboot3_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: r@In4ugust